# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Akkuman Github Pages

on:
  push:
    branches:
      - hugo

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.87.0'

    - name: Build
      run: hugo --minify

    - name: WithGit
      run: |
        # 拉取主仓库
        git clone https://github.com/$GITHUB_REPOSITORY.git .deploy_git
        # 将先前生成的html丢入仓库
        cp -R ./public/* .deploy_git/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/hugo' }}
      with:
        github_token: ${{ secrets.DEPLOY_PAGES_TOKEN }}
        publish_dir: ./.deploy_git
        publish_branch: master

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: "14.x"

    - name: Push to cnblogs
      env:
        CNBLOGS_APPKEY: Akkuman
        CNBLOGS_USERNAME: Akkuman
        CNBLOGS_PASSWORD: ${{ secrets.CNBLOGS_PWD }}
        HOME_DIR: .
      run: |
        echo "ready to pulish to cnblogs"
        npm install metaweblog-api markdown-yaml-metadata-parser
        node publish_to_cnblogs.js $CNBLOGS_APPKEY $CNBLOGS_USERNAME $CNBLOGS_PASSWORD $HOME_DIR