# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Akkuman Github Pages

on:
  push:
    branches:
      - hexo

env:
  REPOADDR: github.com/akkuman/akkuman.github.io.git

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
      export TZ='Asia/Shanghai'
      npm install hexo-cli -g
      npm install
      hexo clean
      hexo g
      set -ev
      git clone https://$REPOADDR .deploy_git
      mv ./public/* .deploy_git/
      cd .deploy_git/
      git config user.name "Akkuman"
      git config user.email "akkumans@qq.com"
      git add .
      git commit -m "Github Action Auto Builder at `date +"%Y-%m-%d %H:%M"`"
      git push --force --quiet "https://${{ secrets.DEPLOY_PAGES_TOKEN }}@$REPOADDR" master:master
      
